version: '3.4'

services:
  garagebot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USER_SECRETS_ID=044a981f-8e29-4023-bf7c-a863075a044e
      - GarageBotHub=http://web/garageHub
      - TestVar=web
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets/:/root/.microsoft/usersecrets 
    
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - GarageBotHub=http://web/garageHub
    ports:
      - "60079:80"
      - "44371:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
      - ${USERPROFILE}\.aspnet\https:/https/
